sudo: required
services:
  -  docker

before_install:
  - docker build -t cristian6407/docker-react -f Dockerfile.dev .

script:
  - docker -e CI=true run -it cristian6407/docker-react npm run test

language: generic
