language: node_js
sudo: required
services:
  -  docker

before_install:
  - docker build -t cristian6407/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cristian6407/docker-react npm run test

